### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by zekun-li** [machines-reading-maps/mapkurator-system#1]
- [ ] Merge split polygons when generating map-level result from patch-level result (polygon + string). @zekun-li 
- [x] Update geotiff generation module to handle polynomial(2-order) and TPS transform. @zekun-li 

- [ ] Module 4. Get transformation matrix from geotiff metadata @Jina-Kim 
- [ ] Module 5. Add Min's approach for the threshold @Jina-Kim 
- [x] Generate ground control points column in metadata csv file @Jina-Kim 

- [x] Convert SID to jpg file in the pipeline  @zekun-li 
- [x] Handle large image files @zekun-li 
- [x] Add log info and time usage info for the modules 1-3 @zekun-li 
- [x] Module 5. Link corresponding entities to OpenStreetMap @Jina-Kim

**Comment by linyijun** [comment]
Train the TEXTR model for text detection and recognition using synthetic maps @Yijun-Lin

**Comment by MinNamgung** [comment]
- [ ] Add module 6. evaluation on Github @Min-Namgung
- [ ] Post-OCR correction (currently working on) @Min-Namgung
